# Generated by Django 4.1.3 on 2023-03-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='fromrrp',
            field=models.BooleanField(default=True, verbose_name='Из реестра рекомендованных поставщиков'),
        ),
    ]
