# Generated by Django 4.1.3 on 2023-04-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_suppliers_fromrrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('reg_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код региона')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AddField(
            model_name='suppliers',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.regions'),
        ),
    ]
