# Generated by Django 4.1.3 on 2023-04-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_regions_suppliers_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={'ordering': ('title',), 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'ordering': ('-fromrrp',), 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.regions', verbose_name='Регион регистрации'),
        ),
    ]
