# Generated by Django 4.1.3 on 2022-12-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронная почта')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('firm_name', models.TextField(verbose_name='Название организации')),
                ('fio', models.TextField(verbose_name='ФИО контакта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты для обратной связи',
            },
        ),
    ]
