# Generated by Django 4.1.3 on 2022-12-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INN', models.CharField(max_length=32, verbose_name='ИНН')),
                ('title', models.CharField(max_length=320, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронная почта')),
                ('address', models.CharField(max_length=1320, verbose_name='Адрес')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('site_url', models.URLField(max_length=320, verbose_name='Сайт')),
                ('price', models.FileField(upload_to='', verbose_name='Прайс-лист')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Supplier_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320, verbose_name='Название')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_site.suppliers')),
            ],
            options={
                'verbose_name': 'Товар поставщика',
                'verbose_name_plural': 'Товары поставщиков',
            },
        ),
    ]
