# Generated by Django 4.1.3 on 2023-03-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_contacts_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='oerder_index',
            field=models.IntegerField(default=0, verbose_name='Приоритет'),
        ),
    ]
