# Generated by Django 4.1.3 on 2023-03-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='full_title',
            field=models.CharField(default='', max_length=1320, verbose_name='Полное название'),
        ),
    ]
