# Generated by Django 4.1.3 on 2023-03-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_suppliers_full_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='KPP',
            field=models.CharField(default='', max_length=32, verbose_name='КПП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers',
            name='OGRN',
            field=models.CharField(default='', max_length=32, verbose_name='ОГРН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers',
            name='post_address',
            field=models.CharField(default='', max_length=1320, verbose_name='Адрес почтовый'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers',
            name='type',
            field=models.CharField(default='', max_length=32, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='address',
            field=models.CharField(max_length=1320, verbose_name='Адрес фактический'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='price',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Прайс-лист'),
        ),
    ]
