# Generated by Django 4.1.3 on 2023-03-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_fileforsearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileForSearch',
        ),
        migrations.DeleteModel(
            name='Supplier_products',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
