# Generated by Django 4.1.3 on 2023-03-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_delete_fileforsearch_delete_supplier_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=300, verbose_name='ФИО')),
                ('about', models.TextField(verbose_name='Биография')),
                ('Photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('JobFunction', models.CharField(max_length=36, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководство',
            },
        ),
    ]
