# Generated by Django 4.1.3 on 2023-03-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managers',
            options={'ordering': ('order_index',), 'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководство'},
        ),
        migrations.AddField(
            model_name='managers',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='Очередность сортировки'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='Photo',
            field=models.ImageField(upload_to='pictures/managers', verbose_name='Фото'),
        ),
    ]
