# Generated by Django 4.1.3 on 2023-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_alter_managers_options_managers_order_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя компании')),
                ('site_url', models.URLField(verbose_name='Сайт партнера')),
                ('logo', models.ImageField(upload_to='pictures/pertners_logo', verbose_name='Лого')),
                ('order_index', models.IntegerField(default=0, verbose_name='Очередность сортировки')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ('order_index',),
            },
        ),
    ]
