# Generated by Django 4.1.3 on 2023-03-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='detail',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='services',
            name='url_page',
            field=models.URLField(default=None, null=True, verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='services',
            name='url_type',
            field=models.IntegerField(choices=[(0, 'Без ссылки'), (1, 'На страницу'), (2, 'На описание')], default=0, verbose_name='Тип ссылки'),
        ),
    ]
