# Generated by Django 4.1.3 on 2023-03-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_services_detail_services_url_page_services_url_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Имя слайда')),
                ('image', models.ImageField(upload_to='pictures/slader_frames', verbose_name='Картинка слайдера')),
                ('order_index', models.IntegerField(default=0, verbose_name='Очередность сортировки')),
                ('slider_tag', models.CharField(max_length=6, verbose_name='Уникальный тэг слайдера')),
            ],
            options={
                'verbose_name': 'Кадр слайдера',
                'verbose_name_plural': 'Кадры сладера',
                'ordering': ('order_index',),
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='detail',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='url_page',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Страница'),
        ),
    ]
